export const CREATING_USER = 'CREATING_USER';
export const CREATED_USER = 'CREATED_USER';
export const RECEIVED_ERROR = 'RECEIVED_ERROR';

export const LOGGING_USER = 'LOGGING_USER';
export const USER_LOGGED = 'USER_LOGGED';

export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const UPDATING_USER_CATEGORIES = 'UPDATING_USER_CATEGORIES';
export const USER_CATEGORIES_UPDATED = 'USER_CATEGORIES_UPDATED';