export const CREATING_USER = 'CREATING_USER';
export const CREATED_USER = 'CREATED_USER';
export const RECEIVED_ERROR = 'RECEIVED_ERROR';

export const LOGGING_USER = 'LOGGING_USER';
export const USER_LOGGED = 'USER_LOGGED';

export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const UPDATING_USER_CATEGORIES = 'UPDATING_USER_CATEGORIES';
export const USER_CATEGORIES_UPDATED = 'USER_CATEGORIES_UPDATED';

export const LISTING_USER_GROUPS = 'LISTING_USER_GROUPS';
export const LIST_USER_GROUPS_FAILED = 'LIST_USER_GROUPS_FAILED';
export const LIST_USER_GROUPS_SUCCESSFUL = 'LIST_USER_GROUPS_SUCCESSFUL';

export const SEARCHING_GROUPS = 'SEARCHING_GROUPS';
export const SEARCH_GROUPS_FAILED = 'SEARCH_GROUPS_FAILED';
export const SEARCH_GROUPS_SUCCESSFUL = 'SEARCH_GROUPS_SUCCESSFUL';

export const SET_MAIN_TITLE = 'SET_MAIN_TEXT';

export const GETTING_GROUP = 'GET_GROUP';
export const GET_GROUP_FAILED = 'GET_GROUP_FAILED';
export const GET_GROUP_SUCCESSFUL = 'GET_GROUP_SUCCESSFUL';