export const RESET_ERROR = 'RESET_ERROR';
export const SET_MAIN_TITLE = 'SET_MAIN_TITLE';


export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const CATEGORIES_LOADED_SUCCESSFUL = 'CATEGORIES_LOADED';
export const LOAD_CATEGORIES_FAILED = 'LOAD_CATEGORIES_FAILED';


export const CREATING_USER = 'CREATING_USER';
export const USER_CREATED_SUCCESSFUL = 'USER_CREATED';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const SENDING_VERIFICATION_EMAIL = 'SENDING_VERIFICATION_EMAIL';
export const EMAIL_VERIFICATION_SENT_SUCCESSFUL = 'EMAIL_VERIFICATION_SENT_SUCCESSFUL';
export const SEND_EMAIL_VERIFICATION_FAILED = 'SEND_EMAIL_VERIFICATION_FAILED';

export const VERIFYING_EMAIL = 'VERIFYING_EMAIL';
export const EMAIL_VERIFIED_SUCCESSFUL = 'EMAIL_VERIFIED_SUCCESSFUL';
export const EMAIL_VERIFY_FAILED = 'EMAIL_VERIFY_FAILED';

export const LOGGING_USER = 'LOGGING_USER';
export const USER_LOGGED_SUCCESSFUL = 'USER_LOGGED_SUCCESSFUL';
export const LOG_USER_FAILED = 'LOG_USER_FAILED';

export const GETTING_USER = 'GETTING_USER';
export const USER_GOT_SUCCESSFUL = 'USER_GOT_SUCCESSFUL';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const UPDATING_USER_CATEGORIES = 'UPDATING_USER_CATEGORIES';
export const USER_CATEGORIES_UPDATED_SUCCESSFUL = 'USER_CATEGORIES_UPDATED_SUCCESSFUL';
export const UPDATE_USER_CATEGORIES_FAILED = 'UPDATE_USER_CATEGORIES_FAILED';


export const LISTING_USER_GROUPS = 'LISTING_USER_GROUPS';
export const USER_GROUPS_LISTED_SUCCESSFUL = 'USER_GROUPS_LISTED_SUCCESSFUL';
export const LIST_USER_GROUPS_FAILED = 'LIST_USER_GROUPS_FAILED';

export const SEARCHING_GROUPS = 'SEARCHING_GROUPS';
export const SEARCH_GROUPS_FAILED = 'SEARCH_GROUPS_FAILED';
export const GROUPS_SEARCHED_SUCCESSFUL = 'GROUPS_SEARCHED_SUCCESSFUL';

export const GETTING_GROUP = 'GETTING_GROUP';
export const GET_GROUP_SUCCESSFUL = 'GET_GROUP_SUCCESSFUL';
export const GET_GROUP_FAILED = 'GET_GROUP_FAILED';

export const UPDATING_USER_MEMBERSHIP = 'UPDATING_USER_MEMBERSHIP';
export const USER_MEMBERSHIP_UPDATED_SUCCESSFUL = 'USER_MEMBERSHIP_UPDATED_SUCCESSFUL';
export const UPDATED_USER_MEMBERSHIP_FAILED = 'UPDATED_USER_MEMBERSHIP_FAILED';

export const UPDATING_GROUP = ' UPDATING_GROUP';
export const GROUP_UPDATE_SUCCESSFUL = ' GROUP_UPDATE_SUCCESSFUL';
export const UPDATE_GROUP_FAILED = ' UPDATE_GROUP_FAILED';

export const CREATING_GROUP = ' CREATING_GROUP';
export const GROUP_CREATED_SUCCESSFUL = ' GROUP_CREATED_SUCCESSFUL';
export const CREATE_GROUP_FAILED = ' CREATE_GROUP_FAILED';
